repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files  # Prevent giant files from being committed
    -   id: check-ast  # Check that files parse as valid Python
    -   id: check-byte-order-marker  # Check for files with a UTF-8 byte-order marker
    -   id: check-case-conflict  # Check for files with names that would conflict on case-insensitive filesystems
    -   id: check-docstring-first  # Check that docstrings are present and at the top of the file
    -   id: check-json  # Check JSON files for parse errors
    -   id: check-merge-conflict  # Check for files that contain merge conflict strings
    -   id: check-toml  # Check TOML files for parse errors
    -   id: check-yaml  # Check YAML files for parse errors
    -   id: debug-statements  # Check for debugger imports and breakpoints
    -   id: end-of-file-fixer  # Ensure files end with a newline
    -   id: mixed-line-ending  # Ensure consistent line endings
        args: [--fix=lf]
    -   id: requirements-txt-fixer  # Sort requirements.txt files
    -   id: trailing-whitespace  # Trim trailing whitespace

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        language_version: python3.9

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        types: [py]
        args: [--profile=black]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear==23.7.10]
        args: [--config=setup.cfg]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-python-dateutil, types-requests, types-PyYAML]
        args: [--strict, --ignore-missing-imports]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa  # Check for blanket noqa
    -   id: python-check-blanket-type-ignore  # Check for blanket type: ignore
    -   id: python-no-log-warn  # Check for deprecated warn() method
    -   id: python-use-type-annotations  # Check for missing type annotations

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
    -   id: prettier
        types: [markdown, yaml, json, html, css, scss, javascript, typescript, jsx, tsx, graphql]
        additional_dependencies:
          - prettier@3.0.3
          - prettier-plugin-sort-json@3.1.0
          - prettier-plugin-toml@0.3.1

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    -   id: mdformat
        additional_dependencies: [mdformat-gfm, mdformat-toc, mdformat-black, mdformat-footnote]
        args: [--wrap=88]
        types: [markdown]
