version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    container_name: python-app
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/app
    command: >
      bash -c "python -m pip install --upgrade pip &&
               pip install -e '.[dev]' &&
               python -m src.main"
    working_dir: /app
    stdin_open: true
    tty: true
    networks:
      - app-network

  # Add other services here (e.g., PostgreSQL, Redis, etc.)
  # postgres:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=mydb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   networks:
  #     - app-network

  # redis:
  #   image: redis:6
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  # postgres_data:
  # redis_data:
