[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "env-dev-prod"
version = "0.1"
requires-python = ">=3.6"
dependencies = [
    # 의존성 목록
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["my_app*", "config*"]
namespaces = false
