[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "env-dev-prod"
version = "0.1"
requires-python = ">=3.6"
dependencies = [
    # 여기에 필요한 패키지들을 추가하세요
]

[tool.setuptools]
package-dir = { "" = "." }

[tool.setuptools.packages.find]
where = ["src", "."]
include = ["my_app", "config"]
namespaces = false
